# Generated by Django 3.2.7 on 2022-03-01 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counselor_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TestTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('test_code', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='TestPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_purchased', models.DateTimeField()),
                ('test_status', models.CharField(max_length=50)),
                ('test_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.testtypes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('confirmation_id', models.CharField(max_length=100, unique=True)),
                ('quantity', models.IntegerField()),
                ('delivery_status', models.CharField(blank=True, choices=[('Delivered', 'Delivered'), ('Pending', 'Pending')], max_length=15)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.testtypes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GiftsPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_code', models.CharField(max_length=100)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.testpurchase')),
            ],
        ),
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_scheduled', models.DateTimeField()),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.counselor')),
                ('test_to_be_discussed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.testtypes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
